django19/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from rest_framework_jwt.views import obtain_jwt_token

from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls", namespace='comments')),

    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^register/', register_view, name='register'),
    url(r'^', include("posts.urls", namespace='posts')),
    url(r'^api/auth/token/', obtain_jwt_token),
    url(r'^api/users/', include("accounts.api.urls", namespace='users-api')),
    url(r'^api/comments/', include("comments.api.urls", namespace='comments-api')),
    url(r'^api/posts/', include("posts.api.urls", namespace='posts-api')),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/api/urls.py
from django.conf.urls import  url
from django.contrib import admin

from .views import (
        PostCreateAPIView,
        PostDetailsAPIView,
        PostDeleteAPIView,
        PostListAPIView,
        PostUpdateAPIView

    )


urlpatterns = [
    url(r'^$', PostListAPIView.as_view(), name='list'),
    url(r'^create/$', PostCreateAPIView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', PostDetailsAPIView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', PostUpdateAPIView.as_view(), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', PostDeleteAPIView.as_view(), name='delete'),
]

posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import(
post_list,
post_create,
post_detail,
post_update,
post_delete
)


urlpatterns = [
    url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
]

posts/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import  slugify

from markdown_deux import markdown

from comments.models import Comments

from .utils import get_read_time


# Create your models here.
# MVC MODEL VIEW CONTROLLER

# Post.objects.all()
# Post.objects.create(user = user, title="Some title" )

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        #Post.objects.all() = super(PostManager, self).all()
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())

def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
    #extension = filename.split(".")
    return "%s/%s" % (instance.id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=128)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True,
                              width_field="width_field",
                              height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time = models.IntegerField(default=0) #models.TimeField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})
        #return "/posts/%s/" %(self.id)

    def get_api_url(self):
        return reverse("posts-api:detail", kwargs={"slug": self.slug})
        #return "/posts/%s/" %(self.id)

    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property
    def comments(self):
        instance = self
        qs = Comments.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
        ]

posts/api/views.py
from django.db.models import Q

from rest_framework.filters import (
    SearchFilter,
    OrderingFilter
)

from rest_framework.generics import (
    CreateAPIView,
    DestroyAPIView,
    ListAPIView,
    RetrieveAPIView,
    UpdateAPIView,
    RetrieveUpdateAPIView
    )


from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,
    )

from posts.models import Post

from .pagination import PostLimtOffsetPagination, PostPageNumberPagination


from .permissions import IsOwnerOrReadOnly

from .serializers import (
    PostCreateUpdateSerializer,
    PostListSerializer,
    PostDetailsSerializer
    )

class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    #permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

class PostDetailsAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailsSerializer
    permission_classes = [AllowAny]
    lookup_field = "slug"
   # lookup_url_kwarg = "abc"

class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    lookup_field = "slug"
   # lookup_url_kwarg = "abc"
    permission_classes = [IsOwnerOrReadOnly]

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)

class PostDeleteAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailsSerializer
    permission_classes = [IsOwnerOrReadOnly]
    lookup_field = "slug"
   # lookup_url_kwarg = "abc"

class PostListAPIView(ListAPIView):
    serializer_class = PostListSerializer
    permission_classes = [AllowAny]
    filter_backends = [SearchFilter]
    search_fields = ['title','content','user__first_name']

    pagination_class = PostPageNumberPagination

    def get_queryset(self, *args, **kwargs):
        #queryset_list = super(PostListAPIView, self).get_queryset(*args, **kwargs)
        queryset_list = Post.objects.all() # filter(user= self.request.user)
        query = self.request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(user__first_name__icontains=query) |
                Q(user__last_name__icontains=query)
            ).distinct()
        return queryset_list

posts/views.py
from urllib.parse import urlparse

from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import  HttpResponse, HttpResponseRedirect , Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

# Create your views here.
from comments.forms import CommentForm
from comments.models import Comments
from .forms import PostForm
from .models import Post


def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    if not request.user.is_authenticated():
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        #print(form.cleaned_data.get("title"))
        instance.user = request.user
        instance.save()


    # if request.method == "POST":
    #     print(request.POST.get("content"))
    #     print(request.POST.get("title"))
        #Post.objects.create(title=title)
        #message success
        messages.success(request, "Successfully created.")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "form": form,
    }
    return render(request, "post_form.html", context)

def post_detail(request, slug=None): # retrive
    #instance = Post.objects.get(id=1)
    instance = get_object_or_404(Post, slug=slug)
    if instance.publish > timezone.now().date() or instance.draft:
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = urlparse(instance.content)

    inital_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id
    }
    form = CommentForm(request.POST or None, initial = inital_data)
    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get("object_id")
        parent_obj = None
        try:
            parent_id = int(request.POST.get('parent_id'))
        except:
            parent_id = None

        if parent_id:
            parent_qs = Comments.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()



        content_data = form.cleaned_data.get("content")

        new_comments, created = Comments.objects.get_or_create(
                        user = request.user,
                        content_type = content_type,
                        object_id = obj_id,
                        content = content_data,
                        parent = parent_obj,
                    )
        return HttpResponseRedirect(new_comments.content_object.get_absolute_url())

    comments = instance.comments#Comments.objects.filter_by_instance(instance)

    context = {
        'title': instance.title,
        'instance':instance,
        'share_string': share_string.path,
        'comments':comments,
        'comment_form':form,
    }
    return render(request, "post_detail.html", context)
    #return HttpResponse("<h1>Detail</h1>")

def post_list(request): # list_items
    today = timezone.now().date()
    queryset_list = Post.objects.active() #.order_by("-timestamp")
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()

    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
        ).distinct()
    paginator = Paginator(queryset_list, 2)  # Show 25 contacts per page
    page_request_var = "abc"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        'object_list': queryset,
        'title': "List",
        'page_request_var': page_request_var,
        'today': today,
    }
    # else:
    #     context = {
    #            'title': "List"
    #     }
    return render(request, "post_list.html", context)



def post_update(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None,request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        print(form.cleaned_data.get("title"))
        instance.save()
        # message success
        messages.success(request, "<a href='#'>Successfully Updated.</a>", extra_tags='html_safe')
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'title': instance.title,
        'instance': instance,
        'form':form,
    }
    return render(request, "post_form.html", context)


def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, "Successfully Deleted.")
    return redirect("posts:list")

templates/base.html
{% load staticfiles %}
<!--DOCTYPE html  -->
<html>
<head>
    <title>{% block head_title  %} Try Django 1.9 {% endblock head_title %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <style>
        {% block style %}
        {% endblock style %}
    </style>
    {% block head_extra %} {% endblock head_extra %}
</head>
<body>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.12&appId=1920392064893369&autoLogAppEvents=1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>



{% include "messages_display.html" %}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'posts:list' %}">Home</a></li>
        {% block post_detail_link %}
        {% endblock %}

        {% if not request.user.is_authenticated %}
        <li class="pull_right"><a href="{% url 'register' %}">Register</a> </li>
        <li class="pull_right"><a href="{% url 'login' %}">login</a> </li>
        {% else %}
        <li class="pull_right"><a href="{% url 'logout' %}">logout</a> </li>
        {% endif %}
    </ol>
    {% block contant %}
    {% endblock contant %}
</div>


<!-- Latest compiled and minified JavaScript -->
<script src="http://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.17/marked.min.js"></script>

<script type="text/javascript">
    $(document).ready(function(){
        $(".content-markdown").each(function(){
            var content = $(this).text()

            var markedContent = marked(content)

            $(this).html(markedContent)
        })
        $(".post-detail-item img").each(function(){
            $(this).addClass("img-responsive");
        })

        var contentInput = $("#id_content");

        function setContent(value){
            var markedContent = marked(value)
            $("#preview-content").html(markedContent);
            $("#preview-content img").each(function(){
                $(this).addClass("img-responsive")
            })
        }
        setContent(contentInput.val())

        contentInput.keyup(function(){
            var newContent = $(this).val()
            setContent(newContent)
        })


        var titleInput = $("#id_title");

        function setTitle(value){
            $("#preview-title").text(value)
        }
        setTitle(titleInput.val())

        titleInput.keyup(function(){
            var newContent = $(this).val()
            setTitle(newContent)
        })

        $(".comment-reply-btn").click(function(event){
            event.preventDefault();
            $(this).parent().next(".comment-reply").fadeToggle("slow")
        })

        // preview content

    });
</script>
</body>
</html>

templates/comment_thread.html
{% extends "base.html" %}
{% load urlfy %}
{% load crispy_forms_tags %}


{% block head_title %}
    {{ instance.title }}| {{ block.super }}
{% endblock head_title %}


{% block contant %}

{{ commentsss }}

<div class="col-sm-6 col-sm-offset-3">



          <p>{{ comments.content }}</p>
          <footer>via {{ comments.user }} on {{ comments.timestamp|timesince }} app
              | {% if comments.children.count > 0 %}{{ comments.children.count }} Comment
              {% if comments.children.count > 1 %}s{% endif %}{% endif %}
              {% if request.user == comments.user %}<a href="{{ comments.get_delete_url }}"> Delete </a>{% endif %}</footer>
            <hr/>
            <div>
                {% for child_comment in comments.children %}
                <blockquote>
                  <p>{{ child_comment.content }}</p>
                    <footer>via {{ child_comment.user }} on {{ child_comment.timestamp|timesince }} app
                        | {% if request.user == child_comment.user %}
                        <a href="{{ child_comment.get_delete_url }}"> Delete </a>{% endif %}
                    </footer>
                </blockquote>
                {% endfor %}
                {% if request.user.is_authenticated %}
                <form method="post" action=".">{% csrf_token %}
                    {{ form|crispy }}
                    <input type="hidden" name="parent_id" value="{{ comments.id }}">
                    <input type="submit" value="Reply" class="btn btn-default">
                </form>
                {% else %}
                <p> You must login to comment </p>
                {% endif %}
            </div>

        <hr/>

</div>

{% endblock contant %}

templates/confirm_delete.html
{% extends "base.html" %}
{% load urlfy %}
{% load crispy_forms_tags %}


{% block head_title %}
    {{ instance.title }}| {{ block.super }}
{% endblock head_title %}


{% block contant %}

{{ commentsss }}

<div class="col-sm-6 col-sm-offset-3">
<h1>Confirm Delete</h1>

                <form method="post" action=".">{% csrf_token %}
                    <p> Are you sure you want to delete : "{{ object.content }}"? </p>
                    <input type="submit" value="Confirm" class="btn btn-warning">
                    <a href="{{ object.get_absolute_url }}" class="btn btn-default">Cancel</a>
                </form>
            </div>

        <hr/>

</div>

{% endblock contant %}

templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block contant %}
<div class="col-sm-6 col-sm-offset-3">
<h1>{{  title }}</h1>

<form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
{{ form|crispy }}

<input type="submit" class="btn btn-default" value="{{ title }}"/>
</form>
</div>
{% endblock contant %}

templates/messages_display.html
{% if messages %}
    <div class="message">

        <ul class="messages">
            {% for message in messages  %}
            <li {% if message.tags %} class="{{ message.tags  }}" {% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
            {% endfor %}
        </ul>

    </div>
{% endif  %}

templates/post_detail.html
{% extends "base.html" %}
{% load urlfy %}
{% load crispy_forms_tags %}


{% block head_title %}
    {{ instance.title }}| {{ block.super }}
{% endblock head_title %}

{% block post_detail_link %}
<li><a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a> </li>
{% endblock %}

<style>
   {% block style %}
   h1{
    color: #777777;
   }
   {% endblock style %}
</style>

{% block contant %}

<div class="col-sm-6 col-sm-offset-3">
    {% if instance.image %}
    <img src="{{ instance.image.url }}" class="img-resp"/>
    {% endif %}
    <!--{% if instance.read_time <= 1 %} < 1 Minute {% else %}{{ instance.read_time }} minutes {% endif %} -->
<h1>{{ title }}  <small>{% if instance.draft %}<span style="color:red"> Draft  </span> {% endif %}{{ instance.publish }}</small></h1>
<p>Read Time: {% if instance.read_time <= 1 %} < 1 Minute {% else %}{{ instance.read_time }} minutes {% endif %} </p>
{% if instance.user.get_full_name %}
    <p>Author: {{ instance.user.get_full_name }}</p>
    {% endif %}



    <p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div></p>
    <hr/>

<!--


    <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
Facebook
</a>
    <a href="https://twitter.com/home?status={{ instance.content|urlfy }}%20{{ request.build_absolute_uri }}">
Twitter
</a>
    <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title=Be%20first%20%7C%20Join%20Swift%20for%20Entrepreneurs&summary=Swift%20for%20Entrepreneurs%20is%20a%20project-based%20programming%20course%20for%20non-technical%20founders.%20We'll%20learn%20how%20to%20build%20iOS%20apps%20from%20scratch%20using%20Apple's%20new%20programming%20language:%20Swift.%20Be%20first%20and%20learn%20with%20me!&source={{ request.build_absolute_uri }}">
Linkedin
</a>
    <a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}&title=Unlock%20to%20Learn%20Swift%20for%20Free!%20By%20Swift%20for%20Entrepreneurs.%20Made%20for%20Non%20Techincals.">Reddit</a>

    <a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>Google+</a>
-->

<div class="row">
<div class="col-sm-12">

    <div class="post-detail-item">{{ instance.get_markdown }}</div>
<hr/>
    <div>
        <p class="lead">Comments</p>
        {% if request.user.is_authenticated %}
        <form method="post" action=".">{% csrf_token %}
            {{ comment_form|crispy }}
            <input type="submit" value="Post Comment" class="btn btn-default">
        </form>
        {% else %}
        <p> You must login to comment </p>
        {% endif %}
        <hr/>
        {% for comments in comments %}


        <blockquote>
          <p>{{ comments.content }}</p>
          <footer>via {{ comments.user }} on {{ comments.timestamp|timesince }} app | {% if comments.children.count > 0 %}{{ comments.children.count }} Comment{% if comments.children.count > 1 %}s{% endif %}{% endif %} | <a href="#" class="comment-reply-btn">Reply</a> | <a href="{{ comments.get_absolute_url }}" class="">Thread</a> </footer>
            <div class="comment-reply">
                {% for child_comment in comments.children %}
                <blockquote>
                  <p>{{ child_comment.content }}</p>
                    <footer>via {{ child_comment.user }} on {{ child_comment.timestamp|timesince }} app </footer>
                </blockquote>
                {% endfor %}
                {% if request.user.is_authenticated %}
                <form method="post" action=".">{% csrf_token %}
                    {{ comment_form|crispy }}
                    <input type="hidden" name="parent_id" value="{{ comments.id }}">
                    <input type="submit" value="Reply" class="btn btn-default">
                </form>
                {% else %}
                <p> You must login to comment </p>
                {% endif %}
            </div>
        </blockquote>
        <hr/>
        {% endfor %}
    </div>
</div>
    </div>
</div>

{% endblock contant %}

templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_extra %}

{{ form.media }}

{% endblock head_extra %}

{% block contant %}
<div class="col-sm-6">
    <h1>Preview</h1>
    <div class="content-preview">
        <h3 id="preview-title"></h3>

        <p id="preview-content"></p>
    </div>
</div>
<div class="col-sm-6">
<h1>Form</h1>

<form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
{{ form|crispy }}

<input type="submit" class="btn btn-default" value="Create Post"/>
</form>
</div>
{% endblock contant %}

templates/post_list.html
{% extends "base.html" %}
    {% block contant %}


<div class="col-sm-6 col-sm-offset-3">
    <h1>{{ title }} is working!</h1>
<form action="" method="GET" class="row">
    <div class="col-sm-6">
    <div class="input-group">
        <input class="form-control" type="text" placeholder="Search Posts" name="q" value="{{ request.GET.q }}"/>
        <span class="input-group-btn">
            <!--<input class="btn btn-default" type="submit" value="submit">-->
            <button class="btn btn-default" type="submit">Search <i class="fa fa-search"></i></button>
        </span>
    </div>
        </div>
</form>
    {% for obj in object_list %}
<div class="row">
  <div class="col-sm-12">
    <div class="thumbnail">
        {% if obj.image %}
        <img src="{{ obj.image.url }}" class="img-resp"/>
        {% endif %}
      <div class="caption post-detail-item">
          {% if obj.draft %}<h3>Staff Only: Draft</h3>{% if obj.publish > today %}<h3> Staff Only: Future Post</h3>{% endif %}{% endif %}
        <h3><a href="{{ obj.get_absolute_url }}">{{ obj.title }} </a> <small> {{ obj.timestamp|timesince }} ago</small></h3>
          {% if obj.user.get_full_name %}<p>Author: {{ obj.user.get_full_name }}</p>{% endif %}
        {{ obj.get_markdown|truncatechars_html:120 }}
        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">view</a></p>
      </div>
    </div>
  </div>
    <hr/>
</div>
    {% endfor %}


<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>

</div>
    {% endblock contant %}